import{createClient}from"@supabase/supabase-js";import"./style.css";
const sb=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const S={tab:"weeks",view:innerWidth>=900?"board":"day",wi:0,di:0,ch:"instagram",weeks:[],events:[],moments:[],session:null};
const $=x=>document.getElementById(x),E=(x="")=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),NL=x=>E(x||"").replaceAll("\n","<br>");
const DN=["MON","TUE","WED","THU","FRI","SAT","SUN"],CH=["instagram","threads","linkedin","substack","youtube"];
function date(start,i=0){let d=new Date(start+"T12:00:00");d.setDate(d.getDate()+i);return d}
function ds(start,i=0){return date(start,i).toLocaleDateString("en-ZA",{day:"2-digit",month:"short"}).toUpperCase()}
function iso(start,i){return date(start,i).toISOString().slice(0,10)}
function shell(){app.innerHTML=`<header><div><span class=kicker>HYPRFY / LIFE OS</span><h1>ON A MISSION</h1><em>More life. Less excuses.</em></div><span id=status>SYNCED</span><nav>${["weeks","calendar","moments"].map(x=>`<button data-tab=${x} class=${S.tab===x?"active":""}>${x}</button>`).join("")}</nav></header><main id=view></main>`;document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;shell();render()})}
function post(p,ch){if(!p)return`<div class=post><p class=dim>No post planned.</p></div>`;let list=(n,a)=>Array.isArray(a)&&a.length?`<div class=brief><span>${n}</span><ul>${a.map(x=>`<li>${E(x)}</li>`).join("")}</ul></div>`:"";return`<div class=post><div class=format><small>${E(p.fmt||"")}</small><b>${E(p.concept||p.cap||"")}</b></div>${p.plan?`<div class=brief><span>TODAY'S PLAN</span><p>${NL(p.plan)}</p></div>`:""}${list("SHOOT / USE",p.shots)}${list("EXECUTION",p.structure)}${p.onscreen?`<div class=brief><span>ON-SCREEN TEXT</span><h4>${E(p.onscreen)}</h4></div>`:""}${p.cap?`<div class=brief><span>${ch==="threads"?"POST":"CAPTION"}</span><p class=copy>${NL(p.cap)}</p></div>`:""}${list("STORIES",p.stories)}${p.note?`<div class=brief><span>NOTE</span><p>${NL(p.note)}</p></div>`:""}</div>`}
function top(w){return`<div class=topbar><div class=pills>${S.weeks.map((x,i)=>`<button data-w=${i} class=${i===S.wi?"active":""}>W${String(i+1).padStart(2,"0")} <small>${ds(x.start_date)}</small></button>`).join("")}<button id=new>+ NEW</button></div><div class=views>${["board","day","episode"].map(x=>`<button data-v=${x} class=${S.view===x?"active":""}>${x}</button>`).join("")}</div></div>`}
function ephead(w){let beats=w.days.reduce((n,d)=>n+(d.film?.length||0),0);return`<section class=ephead><div><span class=eyebrow>EP. ${String(S.wi+1).padStart(3,"0")} / ${ds(w.start_date)} — ${ds(w.start_date,6)}</span><h2>${E(w.theme)}</h2><em>${E(w.subtitle||"")}</em></div><div class=stats><span><b>6</b> FILM DAYS</span><span><b>${beats}</b> BEATS</span><span><b>1</b> EDIT DAY</span><span><b>1</b> EPISODE</span></div></section>`}
function card(d,i,w){let ev=S.events.find(e=>e.date===iso(w.start_date,i)),mo=S.moments.filter(m=>m.date===iso(w.start_date,i));let f=(d.film||[]).slice(0,5),ig=d.post?.instagram;return`<article class="daycol ${i===6?"publish":""}" data-open=${i}><div class=dayhead><span>${DN[i]} ${ds(w.start_date,i).split(" ")[0]}</span><b>${E(d.tag||d.title)}</b></div>${ev?`<div class="pc event"><span>EVENT</span><strong>${E(ev.title)}</strong></div>`:""}<div class="pc vlog"><span>${i===6?"EPISODE":"VLOG"}</span><strong>${d.film?.length||0} PRODUCTION BEATS</strong>${f.map(x=>`<p>${x.action?"○":"●"} ${E(x.meta||x.line)}</p>`).join("")}${d.film?.length>5?`<small>+${d.film.length-5} MORE</small>`:""}</div><div class="pc social"><span>SOCIAL</span><strong>${E(ig?.fmt||"NO PRIMARY POST")}</strong><p>${E(ig?.concept||ig?.onscreen||"Daily channel plan")}</p></div>${mo.slice(0,2).map(m=>`<div class="pc moment"><span>MOMENT</span><strong>${E(m.title||m.text)}</strong></div>`).join("")}<button class=open data-open=${i}>OPEN DAY</button></article>`}
function board(w){return`${ephead(w)}<section class=board>${w.days.map((d,i)=>card(d,i,w)).join("")}</section>`}
function day(w){let d=w.days[S.di],p=S.ch==="youtube"?d.youtube:d.post?.[S.ch];return`<section class=daytitle><span class=eyebrow>W${String(S.wi+1).padStart(2,"0")} / ${E(w.theme)}</span><h2>${E(d.title)}</h2><em>${E(d.tag||"")}</em></section><div class="pills days">${DN.map((x,i)=>`<button data-d=${i} class=${i===S.di?"active":""}>${x}</button>`).join("")}</div><section class=detail><h3>FILM FOR VLOG</h3><div>${(d.film||[]).map(f=>f.action?`<div class=action><span>ACTION / B-ROLL</span>${E(f.line)}</div>`:`<div class=slate><span>${E(f.meta)}</span><p>“${E(f.line)}”</p></div>`).join("")}</div></section><section class=detail><h3>POST TODAY</h3><div><div class="pills channels">${CH.filter(x=>x!=="youtube"||S.di===6).map(x=>`<button data-c=${x} class=${x===S.ch?"active":""}>${x}</button>`).join("")}</div>${post(p,S.ch)}</div></section>`}
function episode(w){let C=[["COLD OPEN","Strongest moments from the finished week",6],["01 — BACK IN MOTION","10km confidence + Monday world",0],["02 — THE WORK","Office + Rexona + R&D workshop",3],["03 — KEEP SHOWING UP","RunBoss + training thread",1],["04 — PEOPLE BUILDING THINGS","Coastal Coffee / Craig",4],["05 — MORE LIFE","Family / ordinary Saturday",5],["REFLECTION + OUTRO","What the week actually showed you",6]];return`${ephead(w)}<section class=timeline>${C.map(([a,b,i],n)=>`<button data-open=${i}><span>${String(n+1).padStart(2,"0")}</span><div><b>${a}</b><p>${b}</p></div></button>`).join("")}</section>`}
function weeks(){let w=S.weeks[S.wi];if(!w)return view.innerHTML="<p>No week found.</p>";view.innerHTML=top(w)+(S.view==="board"?board(w):S.view==="episode"?episode(w):day(w));document.querySelectorAll("[data-w]").forEach(b=>b.onclick=()=>{S.wi=+b.dataset.w;weeks()});document.querySelectorAll("[data-v]").forEach(b=>b.onclick=()=>{S.view=b.dataset.v;weeks()});document.querySelectorAll("[data-open]").forEach(b=>b.onclick=e=>{e.stopPropagation();S.di=+b.dataset.open;S.view="day";weeks()});document.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>{S.di=+b.dataset.d;S.ch="instagram";weeks()});document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{S.ch=b.dataset.c;weeks()});if($("new"))$("new").onclick=()=>alert("AI week generation is the next beta build.")}
function calendar(){view.innerHTML=`<section class=page><span class=eyebrow>KNOWN DATES</span><h2>CALENDAR</h2><form id=ef><input id=ed type=date required><input id=et placeholder="Event title" required><textarea id=ex placeholder="Description"></textarea><button>Add event</button></form>${S.events.map(e=>`<article class=list><span>${E(e.date)}</span><div><b>${E(e.title)}</b><p>${E(e.description||"")}</p></div><button data-del="${e.id}:events">DELETE</button></article>`).join("")}</section>`;ef.onsubmit=async e=>{e.preventDefault();let{error}=await sb.from("events").insert({date:ed.value,title:et.value,description:ex.value||null});if(error)return alert(error.message);await load();calendar()};dels()}
function moments(){view.innerHTML=`<section class=page><span class=eyebrow>QUICK CAPTURE</span><h2>MOMENTS</h2><form id=mf><input id=md type=date><input id=mt placeholder="Moment title" required><textarea id=mx placeholder="Description" required></textarea><button>Add moment</button></form>${S.moments.map(m=>`<article class=list><span>${E(m.date||"UNDATED")}</span><div><b>${E(m.title||m.text)}</b><p>${E(m.description||m.text||"")}</p></div><button data-del="${m.id}:moments">DELETE</button></article>`).join("")}</section>`;mf.onsubmit=async e=>{e.preventDefault();let{error}=await sb.from("moments").insert({date:md.value||null,title:mt.value,description:mx.value,text:mt.value});if(error)return alert(error.message);await load();moments()};dels()}
function dels(){document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{let[id,t]=b.dataset.del.split(":");if(confirm("Delete?")){await sb.from(t).delete().eq("id",id);await load();render()}})}
function render(){if(!S.session)return view.innerHTML=`<section class=page><h2>SIGN IN</h2><form id=login><input id=email type=email placeholder=Email required><input id=pw type=password placeholder=Password required><button>Sign in</button></form></section>`,login.onsubmit=async e=>{e.preventDefault();let{error}=await sb.auth.signInWithPassword({email:email.value,password:pw.value});if(error)alert(error.message)};({weeks,calendar,moments}[S.tab])()}
async function load(){let[e,m,w]=await Promise.all([sb.from("events").select("*").order("date"),sb.from("moments").select("*").order("created_at",{ascending:false}),sb.from("weeks").select("*").order("start_date")]);S.events=e.data||[];S.moments=m.data||[];S.weeks=w.data||[]}
async function boot(){shell();S.session=(await sb.auth.getSession()).data.session;if(S.session)await load();render();sb.auth.onAuthStateChange(async(_,s)=>{S.session=s;if(s)await load();shell();render()})}boot();